FCP-25 | implement DO authentication
nguyenquangphuc-vn/f0-capstone-project-frontend pull request #4
Opened 2022-04-08 15:16 UTC by phanle11vn

2022-04-09 17:02 UTC, trgianghuynh1808 requested changes

2022-04-09 17:02 UTC, trgianghuynh1808 commented on src/components/pages/AuthenticationPage/components/AuthenticationForm/index.tsx
> +function CloudServiceOptionPage() {
- xem đặt lại tên component nha e a thấy em đặt tên component ở cây thư mực là AuthenticationForm sao trong đây lại là tên khác?
- chỉ khi nào đặt tên cho page mới gọi là Page nha em
- suggest đổi thành: `AuthenticationForm`

2022-04-09 17:02 UTC, trgianghuynh1808 commented on src/components/pages/AuthenticationPage/components/AuthenticationForm/styles.module.scss
> +  margin-bottom: 1em;
không dùng em, rem. vì rất khó kiểm soát. check lại các nơi khác

2022-04-09 17:02 UTC, trgianghuynh1808 commented on src/routes.ts
> +  },
xem đặt lại tên route cho hợp lý hơn nha e. authentication hông nói được ý nghĩa login vào cloud

2022-04-10 06:24 UTC, trgianghuynh1808 approved these changes
LGTM!

2022-04-10 06:47 UTC, nguyenquangphuc-vn approved these changes

2022-04-10 06:48 UTC, merged