FCP-26 | implement UI tabs layout & bandwidth graph
nguyenquangphuc-vn/f0-capstone-project-frontend pull request #8
Opened 2022-04-13 12:12 UTC by phanle11vn

2022-04-13 16:02 UTC, nguyenquangphuc-vn requested changes
![image](https://user-images.githubusercontent.com/39431852/163222490-34fbf652-478d-4167-bd08-92b765e46dde.png)

2022-04-13 16:07 UTC, nguyenquangphuc-vn requested changes
![image](https://user-images.githubusercontent.com/39431852/163223199-1eed22fb-a35b-46f6-b2a4-13d6a1824052.png)
2 bên căn lề trái phải của chart không đều

2022-04-13 16:08 UTC, nguyenquangphuc-vn requested changes
chỉnh lại cho chart container to ra hơn nữa, vì page chỉ có mỗi cái chart container thôi, nên cứ làm gần full luôn

2022-04-14 04:21 UTC, nguyenquangphuc-vn requested changes
chỉnh đường thằng thành đường cong nha ông

2022-04-14 04:22 UTC, nguyenquangphuc-vn requested changes
add thêm dropdown filter

2022-04-16 13:21 UTC, trgianghuynh1808 requested changes

2022-04-16 13:21 UTC, trgianghuynh1808 commented on src/components/pages/MonitoringPage/component/SelectPeriod/index.tsx
> +  }
Không tạo const với function

2022-04-16 13:21 UTC, trgianghuynh1808 commented on src/components/pages/MonitoringPage/component/SelectPeriod/index.tsx
> +  const [dropdownopen, setDropdownopen] = useState(false)
- đổi tên state. sai ngữ pháp
dropdownopen => isOpenDropwdown
- Thêm type cho state ví dụ:
```
const [isOpenDropdown, setIsOpenDropdown] = useState<boolean>(false)
```

2022-04-16 13:21 UTC, trgianghuynh1808 commented on src/components/pages/MonitoringPage/component/SelectPeriod/index.tsx
> +    setDropdownopen((prevState) => !prevState)
không viết tắt

2022-04-16 13:21 UTC, trgianghuynh1808 commented on src/components/pages/MonitoringPage/component/TabsContent/constants.ts
> +]
- k dùng như thế này. vì dùng như vậy. khi thay đổi enum, biến này đâu thay đổi theo.vậy việt tạo enum cho tab là vô nghĩa rồi
- tìm hiểu cách đổi enum thành string array, và sử dụng để render

2022-04-16 14:25 UTC, merged